### ISSUE TITLE
Object of class stdClass could not be converted to string

### ISSUE THREAD

**Issue by oxynaz** [Guisch/autoDLT411#2]
User: httpGroups: http sambashareInitialisation de l'objet t411...
Connexion à l'API...
Récupération des torrents 'Top today'...

Recoverable fatal error: Object of class stdClass could not be converted to string in /var/www/autoDLT411/getTorrent/checkTest.php on line 31

**Comment by Guisch** [comment]
Uhm, ok l'initialisation ce fait bien, c'est bizarre. Tu peux m'en dire plus sur le contexte ? (tu viens de l'installer ou tu ça marchait avant et ça ne marche plus maintenant par exemple).
Est-ce que la page searchTU.php te retourne une erreur ?

**Comment by oxynaz** [comment]
Bonjour, 
je viens d'installer, sur archlinux, nginx, php7-fpm.
la page searchTU.php n'indique pas d'erreurs (en fait elle indique rien quand je lance http://192.168.178.22:88/getTorrent/searchTU.php?=https://www.t411.alXXXXXXXXXXXXXXlapagedutorrent)

**Comment by Guisch** [comment]
Il faut lire le Readme ;)

Il faut retirer le https://t411.al/torrents/ quand tu appelles le
searchTU.php

Réessaye et dit moi


Le 22 mai 2017 08:02, "oxynaz" <notifications@github.com> a écrit :

Bonjour,
je viens d'installer, sur archlinux, nginx, php7-fpm.
la page searchTU.php n'indique pas d'erreurs (en fait elle indique rien
quand je lance http://192.168.178.22:88/getTorrent/searchTU.php?=
https://www.t411.alXXXXXXXXXXXXXXlapagedutorrent)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Guisch/autoDLT411/issues/2#issuecomment-303006575>, or mute
the thread
